#!/opt/homebrew/bin/php

<?php

print "<!DOCTYPE html>";
print "<html>";
print "<head>";
print "  <title></title>";
print "  <style>";
print "  html, body {";
print "    height: 100%;";
print "    margin: 0;";
print "  }";
print "";
print "  body {";
print "    background: black;";
print "    display: flex;";
print "    align-items: center;";
print "    justify-content: center;";
print "  }";
print "  canvas {";
print "    border: 1px solid white;";
print "  }";
print "  </style>";
print "</head>";
print "<body>";
print "<canvas width=\"400\" height=\"400\" id=\"game\"></canvas>";
print "<script>";
print "var canvas = document.getElementById('game');";
print "var context = canvas.getContext('2d');";
print "";
print "var grid = 16;";
print "var count = 0;";
print "  ";
print "var snake = {";
print "  x: 160,";
print "  y: 160,";
print "";
print "  dx: grid,";
print "  dy: 0,";
print "  ";
print "  cells: [],";
print "  ";
print "  maxCells: 4";
print "};";
print "var apple = {";
print "  x: 320,";
print "  y: 320";
print "};";
print "function getRandomInt(min, max) {";
print "  return Math.floor(Math.random() * (max - min)) + min;";
print "}";
print "function loop() {";
print "  requestAnimationFrame(loop);";
print "";
print "  if (++count < 4) {";
print "    return;";
print "  }";
print "";
print "  count = 0;";
print "  context.clearRect(0,0,canvas.width,canvas.height);";
print "";
print "  snake.x += snake.dx;";
print "  snake.y += snake.dy;";
print "";
print "  if (snake.x < 0) {";
print "    snake.x = canvas.width - grid;";
print "  }";
print "  else if (snake.x >= canvas.width) {";
print "    snake.x = 0;";
print "  }";
print "  ";
print "  if (snake.y < 0) {";
print "    snake.y = canvas.height - grid;";
print "  }";
print "  else if (snake.y >= canvas.height) {";
print "    snake.y = 0;";
print "  }";
print "";
print "  snake.cells.unshift({x: snake.x, y: snake.y});";
print "";
print "  if (snake.cells.length > snake.maxCells) {";
print "    snake.cells.pop();";
print "  }";
print "";
print "  context.fillStyle = 'red';";
print "  context.fillRect(apple.x, apple.y, grid-1, grid-1);";
print "";
print "  context.fillStyle = 'green';";
print "  snake.cells.forEach(function(cell, index) {";
print "    ";
print "    context.fillRect(cell.x, cell.y, grid-1, grid-1);  ";
print "";
print "    if (cell.x === apple.x && cell.y === apple.y) {";
print "      snake.maxCells++;";
print "      apple.x = getRandomInt(0, 25) * grid;";
print "      apple.y = getRandomInt(0, 25) * grid;";
print "    }";
print "";
print "    for (var i = index + 1; i < snake.cells.length; i++) {";
print "      ";
print "      if (cell.x === snake.cells[i].x && cell.y === snake.cells[i].y) {";
print "        snake.x = 160;";
print "        snake.y = 160;";
print "        snake.cells = [];";
print "        snake.maxCells = 4;";
print "        snake.dx = grid;";
print "        snake.dy = 0;";
print "";
print "        apple.x = getRandomInt(0, 25) * grid;";
print "        apple.y = getRandomInt(0, 25) * grid;";
print "      }";
print "    }";
print "  });";
print "}";
print "";
print "document.addEventListener('keydown', function(e) {";
print "  if (e.which === 37 && snake.dx === 0) {";
print "    snake.dx = -grid;";
print "    snake.dy = 0;";
print "  }";
print "  else if (e.which === 38 && snake.dy === 0) {";
print "    snake.dy = -grid;";
print "    snake.dx = 0;";
print "  }";
print "  else if (e.which === 39 && snake.dx === 0) {";
print "    snake.dx = grid;";
print "    snake.dy = 0;";
print "  }";
print "  else if (e.which === 40 && snake.dy === 0) {";
print "    snake.dy = grid;";
print "    snake.dx = 0;";
print "  }";
print "});";
print "";
print "requestAnimationFrame(loop);";
print "</script>";
print "</body>";
print "</html>";